services:
  frontend:
    image: node:20
    working_dir: /frontend
    volumes:
      - frontend_node_modules:/frontend/node_modules/
      - ./frontend:/frontend
    ports:
      - 3000:3000
    entrypoint:
      - bash
      - -c
      - "npm ci && npm run dev"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    environment:
      DATABASE_URL: postgres://postgres:postgres-password@db:5432/verband
    volumes:
      - backend_target:/backend/target/
      - ./backend:/backend
    ports:
      - 8000:8000

  nginx:
    image: nginx:1.25.3
    volumes:
      - ./nginx/dev.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:8080

  db:
    image: postgres:16.1-bookworm
    environment:
      POSTGRES_PASSWORD: postgres-password
      POSTGRES_DB: verband
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
  
  meilisearch:
    image: getmeili/meilisearch:v1.5
    environment:
      MEILI_MASTER_KEY: meili-master-key
    volumes:
      - meilisearch:/meili_data

volumes:
  db:
  meilisearch:
  frontend_node_modules:
  backend_target:
